# Generated by Django 4.1.1 on 2022-09-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_iorder_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                related_query_name="customer",
                to="orders.customers",
            ),
        ),
    ]
