# Generated by Django 4.1.1 on 2022-09-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_iorder_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iorder",
            name="order_day",
            field=models.DateField(auto_now_add=True),
        ),
    ]
