# Generated by Django 4.1.1 on 2022-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_iorder_order_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iorder",
            name="order_day",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
